### ISSUE TITLE
Format of the listed links?

### ISSUE THREAD

**Issue by jbranchaud** [jbranchaud/awesome-react-design-systems#2]
Thinking through what the format should be for the links that are being listed in the README.

Right now, it looks like this:

`[Grommet](http://grommet.io/)` which translates to [Grommet](http://grommet.io/).

What if we linked to both the github repo and the respective landing page like so:

`[Grommet](http://grommet.io/) [[github](https://github.com/grommet/grommet)] -- Hewlett Packard`

which would look like:

[Grommet](http://grommet.io/) [[github](https://github.com/grommet/grommet)] -- Hewlett Packard

Thoughts?

**Comment by greis** [comment]
Agree. What if there is no landing page for the link? What would you prefer:

a)  Grommet [[github](https://github.com/grommet/grommet)] -- Hewlett Packard

b) [Grommet](https://github.com/grommet/grommet) -- Hewlett Packard

**Comment by jbranchaud** [comment]
Yeah, I think option **a** is the way to go!

**Comment by jbranchaud** [comment]
We've settled on a format, closing.
